
FROM  mcr.microsoft.com/mssql-tools as mssql
FROM alpine as new-alpine
FROM php:7.4.27-fpm-alpine3.15 as prod

COPY configure.sh /
COPY php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY conf.d/php.prod.ini /usr/local/etc/php
COPY --from=mssql /opt/mssql-tools/ /opt/mssql-tools/
COPY --from=new-alpine /etc/ssl/cert.pem /etc/ssl/cert.pem

RUN /configure.sh \
    && rm /configure.sh
WORKDIR /var/www

FROM prod as dev
COPY docker-dev-entrypoint /usr/local/bin
COPY conf.d/90-xdebug.ini /usr/local/etc/php/conf.d/

RUN apk add --no-cache $PHPIZE_DEPS \
        && pecl install xdebug \
        && docker-php-ext-enable xdebug \
        && apk del $PHPIZE_DEPS

# Fix iconv extension
ENV PHP_VER="7.1.5"
ARG BUILD_PACKAGES="wget build-base php7-dev"

apk add --no-cache --virtual .php-build-dependencies $BUILD_PACKAGES && \
apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ gnu-libiconv-dev && \
(mv /usr/bin/gnu-iconv /usr/bin/iconv; mv /usr/include/gnu-libiconv/*.h /usr/include; rm -rf /usr/include/gnu-libiconv) && \
mkdir -p /opt && \
cd /opt && \
wget https://secure.php.net/distributions/php-$PHP_VER.tar.gz && \
tar xzf php-$PHP_VER.tar.gz && \
cd php-$PHP_VER/ext/iconv && \
phpize && \
./configure --with-iconv=/usr && \
make && \
make install && \
mkdir -p /etc/php7/conf.d && \
echo "extension=iconv.so" >> /etc/php7/conf.d/iconv.ini && \

apk del .php-build-dependencies && \
rm -rf /opt/*
# END Fix iconv extension

ENTRYPOINT ["docker-dev-entrypoint"]
CMD ["php-fpm"]