FROM  mcr.microsoft.com/mssql-tools as mssql
FROM alpine as new-alpine
FROM php:7.4.27-fpm-alpine3.15 as prod

COPY configure.sh /
COPY php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY conf.d/php.prod.ini /usr/local/etc/php
COPY --from=mssql /opt/mssql-tools/ /opt/mssql-tools/
COPY --from=new-alpine /etc/ssl/cert.pem /etc/ssl/cert.pem

RUN /configure.sh \
    && rm /configure.sh
WORKDIR /var/www

FROM prod as dev
COPY docker-dev-entrypoint /usr/local/bin
COPY conf.d/90-xdebug.ini /usr/local/etc/php/conf.d/

RUN apk add --no-cache $PHPIZE_DEPS \
        && pecl install xdebug \
        && docker-php-ext-enable xdebug \
        && apk del $PHPIZE_DEPS

    # Workaround libiconv
    RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
        && apk update && apk upgrade \
        && apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.13/community/ gnu-libiconv=1.15-r3
    ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

ENTRYPOINT ["docker-dev-entrypoint"]
CMD ["php-fpm"]